name: scp files
on: 
   push:
      branches:
           - "main" 
   workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: "appleboy deployment"
        uses: appleboy/ssh-action@v0.1.4
        
        with:
          host: ${{secrets.HOST}}
          
          username: ${{secrets.USERNAME}}
          password: ${{secrets.PASSWORD}}
          
          script: |
            cd ${{secrets.REPO_PATH}}
            echo ${{secrets.PASSWORD}} | sudo -S make redeploy
